// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }



'use client';

import React ,{useEffect} from 'react';
import { ThemeProvider } from '../components/ThemeProvider';
import { WebSocketProvider } from '../context/WebSocketContext';
import { usePathname, useSearchParams } from 'next/navigation';
import i18n from '../../i18n';


//import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  const searchParams = useSearchParams();

  useEffect(() => {
    // Set language from localStorage or default to 'fr'
    const lang = localStorage.getItem('i18nextLng') || 'fr';
    i18n.changeLanguage(lang);
    
    // Update HTML lang attribute
    document.documentElement.lang = lang;
  }, [pathname, searchParams]); // Re-run when route changes


  return (
    <WebSocketProvider>
    <html lang="fr">
      <body className="antialiased">
        <ThemeProvider>
          <div className="min-h-screen">
            <main>{children}</main>
          </div>
        </ThemeProvider>
      </body>
    </html>
    </WebSocketProvider>
  );
}